services:
    app:
        build:
            context: .
            dockerfile: Dockerfile

        restart: unless-stopped

        ports:
            - "127.0.0.1:${APP_PORT}:80"

        env_file:
            - .env

        networks:
            - lumished-network

        healthcheck:
            test: ["CMD", "curl", "-f", "http://127.0.0.1/up"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s

    queue:
        build:
            context: .
            dockerfile: Dockerfile

        restart: unless-stopped

        command:
            - php
            - artisan
            - queue:work
            - --sleep=3
            - --tries=3
            - --timeout=90

        env_file:
            - .env

        networks:
            - lumished-network

    scheduler:
        build:
            context: .
            dockerfile: Dockerfile

        restart: unless-stopped

        command:
            - php
            - artisan
            - schedule:work

        env_file:
            - .env

        networks:
            - lumished-network

networks:
    lumished-network:
        external: true
